import panda as pd

column_names=['JanTem1','JanPre1','FebTem1','FebPre1','MarTem1','MarPre1','AprTem1','AprPre1','MayTem1','MayPre1','JunTem1','JunPre1','JulTem1','JulPre1','AugTem1','AugPre1','SepTem1','SepPre1','OctTem1','OctPre1','NovTem1','NovPre1','DecTem1','DecPre1',
	'JanTem2','JanPre2','FebTem2','FebPre2','MarTem2','MarPre2','AprTem2','AprPre2','MayTem2','MayPre2','JunTem2','JunPre2','JulTem2','JulPre2','AugTem2','AugPre2','SepTem2','SepPre2','OctTem2','OctPre2','NovTem2','NovPre2','DecTem2','DecPre2',
	'JanTem3','JanPre3','FebTem3','FebPre3','MarTem3','MarPre3','AprTem3','AprPre3','MayTem3','MayPre3','JunTem3','JunPre3','JulTem3','JulPre3','AugTem3','AugPre3','SepTem3','SepPre3','OctTem3','OctPre3','NovTem3','NovPre3','DecTem3','DecPre3',
	'JanTem4','JanPre4','FebTem4','FebPre4','MarTem4','MarPre4','AprTem4','AprPre4','MayTem4','MayPre4','JunTem4','JunPre4','JulTem4','JulPre4','AugTem4','AugPre4','SepTem4','SepPre4','OctTem4','OctPre4','NovTem4','NovPre4','DecTem4','DecPre4',
	'JanTem5','JanPre5','FebTem5','FebPre5','MarTem5','MarPre5','AprTem5','AprPre5','MayTem5','MayPre5','JunTem5','JunPre5','JulTem5','JulPre5','AugTem5','AugPre5','SepTem5','SepPre5','OctTem5','OctPre5','NovTem5','NovPre5','DecTem5','DecPre5',
	'JanTem6','JanPre6','FebTem6','FebPre6','MarTem6','MarPre6','AprTem6','AprPre6','MayTem6','MayPre6','JunTem6','JunPre6','JulTem6','JulPre6','AugTem6','AugPre6','SepTem6','SepPre6','OctTem6','OctPre6','NovTem6','NovPre6','DecTem6','DecPre6',
	'JanTem7','JanPre7','FebTem7','FebPre7','MarTem7','MarPre7','AprTem7','AprPre7','MayTem7','MayPre7','JunTem7','JunPre7','JulTem7','JulPre7','AugTem7','AugPre7','SepTem7','SepPre7','OctTem7','OctPre7','NovTem7','NovPre7','DecTem7','DecPre7',
	'JanTem8','JanPre8','FebTem8','FebPre8','MarTem8','MarPre8','AprTem8','AprPre8','MayTem8','MayPre8','JunTem8','JunPre8','JulTem8','JulPre8','AugTem8','AugPre8','SepTem8','SepPre8','OctTem8','OctPre8','NovTem8','NovPre8','DecTem8','DecPre8',
	'JanTem9','JanPre9','FebTem9','FebPre9','MarTem9','MarPre9','AprTem9','AprPre9','MayTem9','MayPre9','JunTem9','JunPre9','JulTem9','JulPre9','AugTem9','AugPre9','SepTem9','SepPre9','OctTem9','OctPre9','NovTem9','NovPre9','DecTem9','DecPre9',
	'JanTem10','JanPre10','FebTem10','FebPre10','MarTem10','MarPre10','AprTem10','AprPre10','MayTem10','MayPre10','JunTem10','JunPre10','JulTem10','JulPre10','AugTem10','AugPre10','SepTem10','SepPre10','OctTem10','OctPre10','NovTem10','NovPre10','DecTem10','DecPre10',
	'JanTemOut','JanPreOut','FebTemOut','FebPreOut','MarTemOut','MarPreOut','AprTemOut','AprPreOut','MayTemOut','MayPreOut','JunTemOut','JunPreOut','JulTemOut','JulPreOut','AugTemOut','AugPreOut','SepTemOut','SepPreOut','OctTemOut','OctPreOut','NovTemOut','NovPreOut','DecTemOut','DecPreOut',
	]